import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';
import 'package:path/path.dart' as p;

/// Catalogue of every runtime source `init` materializes into a target
/// project, each with a content hash.
///
/// Shipped as a package asset (`runtime_assets/manifest.json`, generated by
/// `tool/gen_manifest.dart` — never hand-edited). The hashes power integrity
/// verification at install time and drift detection at removal time.
class RuntimeManifest {
  RuntimeManifest({
    required this.runtimeVersion,
    required this.mainReplacement,
    required this.files,
    this.spatial = false,
  });

  final String runtimeVersion;

  /// Whether this is the SPATIAL (premium) tier. The native tier excludes the
  /// `compositor_ng/` compositor sources and omits the GPU link stack +
  /// `MORPHIC_SPATIAL` define from the CMake block. Premium asset gate, Phase 1.
  final bool spatial;

  /// The `main.cpp` template that replaces the project's runner entrypoint.
  final ManifestEntry mainReplacement;

  /// Runtime sources materialized verbatim into the project.
  final List<ManifestEntry> files;

  /// Every materialized entry (runtime sources + the main replacement).
  List<ManifestEntry> get all => [...files, mainReplacement];

  factory RuntimeManifest.fromJson(Map<String, dynamic> json) =>
      RuntimeManifest(
        runtimeVersion: json['runtimeVersion'] as String,
        spatial: json['spatial'] as bool? ?? false,
        mainReplacement: ManifestEntry.fromJson(
          json['mainReplacement'] as Map<String, dynamic>,
        ),
        files:
            (json['files'] as List)
                .map((e) => ManifestEntry.fromJson(e as Map<String, dynamic>))
                .toList(),
      );

  Map<String, Object> toJson() => {
    'runtimeVersion': runtimeVersion,
    'spatial': spatial,
    'fileCount': files.length + 1,
    'mainReplacement': mainReplacement.toJson(),
    'files': files.map((e) => e.toJson()).toList(),
  };

  /// The manifest filename for a tier. Native (free) is the default
  /// `manifest.json`; the spatial (premium) tier is a separate file so it can
  /// be delivered independently (Phase 2: shipped only after license validation).
  static String fileNameFor({required bool spatial}) =>
      spatial ? 'manifest_spatial.json' : 'manifest.json';

  /// Loads the manifest bundled at [assetsRoot] (the package's
  /// `runtime_assets/` directory). [spatial] selects the premium tier.
  static RuntimeManifest loadBundled(String assetsRoot, {bool spatial = false}) {
    final file = File(p.join(assetsRoot, fileNameFor(spatial: spatial)));
    if (!file.existsSync()) {
      throw StateError(
        spatial
            ? 'Spatial runtime manifest not found at ${file.path}. The spatial '
                'tier is a premium add-on — run `morphic activate <key>` first.'
            : 'Runtime manifest not found at ${file.path}.',
      );
    }
    return RuntimeManifest.fromJson(
      jsonDecode(file.readAsStringSync()) as Map<String, dynamic>,
    );
  }

  /// Verifies every entry's source exists under [assetsRoot] and matches its
  /// recorded hash. Returns a list of problems; empty means intact.
  List<String> verifyAssets(String assetsRoot) {
    final problems = <String>[];
    for (final entry in all) {
      final file = File(p.join(assetsRoot, entry.source));
      if (!file.existsSync()) {
        problems.add('missing asset: ${entry.source}');
      } else if (hashFile(file) != entry.sha256) {
        problems.add('hash mismatch: ${entry.source}');
      }
    }
    return problems;
  }
}

class ManifestEntry {
  ManifestEntry({
    required this.source,
    required this.target,
    required this.sha256,
    required this.kind,
  });

  static const String kindRuntimeSource = 'runtime_source';
  static const String kindMainReplacement = 'main_replacement';

  /// Path of the canonical source, relative to `runtime_assets/`.
  final String source;

  /// Path it materializes to, relative to the target project root.
  final String target;

  /// Expected content hash of the canonical source.
  final String sha256;

  /// [kindRuntimeSource] or [kindMainReplacement].
  final String kind;

  factory ManifestEntry.fromJson(Map<String, dynamic> json) => ManifestEntry(
    source: json['source'] as String,
    target: json['target'] as String,
    sha256: json['sha256'] as String,
    kind: json['kind'] as String,
  );

  Map<String, Object> toJson() => {
    'source': source,
    'target': target,
    'sha256': sha256,
    'kind': kind,
  };
}

String hashFile(File file) => sha256.convert(file.readAsBytesSync()).toString();

String hashBytes(List<int> bytes) => sha256.convert(bytes).toString();
